name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Start app
        env:
          PORT: 3000
          # minimal dummy env so the app can boot
          SENTRY_DSN: http://example.com/123
          SENTRY_SAMPLE_RATE: "0.0"
          SUPABASE_URL: https://example.supabase.co
          SUPABASE_ANON_KEY: test_anon_key
          SLACK_SIGNING_SECRET: test_signing_secret
          SLACK_BOT_TOKEN: xoxb-test
        run: |
          node index.js &>/tmp/app.log &
          for i in {1..20}; do
            curl -fsS http://localhost:3000/api/health && break
            sleep 0.5
          done
          curl -fsS http://localhost:3000/api/health

      - name: OpenAPI check
        env:
          CHECK_BASE_URL: http://localhost:3000
        run: npm run check:openapi

      - name: Smoke tests
        run: bash smoke.sh http://localhost:3000

      - name: Upload app logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: /tmp/app.log
